# Generated by Django 4.2.27 on 2026-01-10 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticaEstrela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrela', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('frequencia', models.PositiveIntegerField(default=0, verbose_name='Frequência Total')),
                ('percentagem', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentagem (%)')),
                ('ultima_aparicao', models.DateField(blank=True, null=True, verbose_name='Última Aparição')),
                ('dias_sem_sair', models.PositiveIntegerField(default=0, verbose_name='Dias Sem Sair')),
                ('gap_medio', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Gap Médio (dias)')),
                ('gap_maximo', models.PositiveIntegerField(default=0, verbose_name='Gap Máximo (dias)')),
                ('desvio_esperado', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Desvio do Esperado')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatística de Estrela',
                'verbose_name_plural': 'Estatísticas de Estrelas',
                'ordering': ['estrela'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticaNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('frequencia', models.PositiveIntegerField(default=0, verbose_name='Frequência Total')),
                ('percentagem', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentagem (%)')),
                ('ultima_aparicao', models.DateField(blank=True, null=True, verbose_name='Última Aparição')),
                ('dias_sem_sair', models.PositiveIntegerField(default=0, verbose_name='Dias Sem Sair')),
                ('gap_medio', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Gap Médio (dias)')),
                ('gap_maximo', models.PositiveIntegerField(default=0, verbose_name='Gap Máximo (dias)')),
                ('desvio_esperado', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Desvio do Esperado')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatística de Número',
                'verbose_name_plural': 'Estatísticas de Números',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data do Sorteio')),
                ('concurso', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número do Concurso')),
                ('numero_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('numero_2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('numero_3', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('numero_4', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('numero_5', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('estrela_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('estrela_2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('jackpot', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Jackpot (€)')),
                ('houve_vencedor', models.BooleanField(default=False, verbose_name='Houve Vencedor?')),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ApostaGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('estrategia', models.CharField(choices=[('frequencia', 'Baseada em Frequência'), ('equilibrada', 'Distribuição Equilibrada'), ('aleatorio', 'Aleatório Puro'), ('frios', 'Números Frios'), ('mista', 'Estratégia Mista')], max_length=20)),
                ('numero_1', models.PositiveSmallIntegerField()),
                ('numero_2', models.PositiveSmallIntegerField()),
                ('numero_3', models.PositiveSmallIntegerField()),
                ('numero_4', models.PositiveSmallIntegerField()),
                ('numero_5', models.PositiveSmallIntegerField()),
                ('estrela_1', models.PositiveSmallIntegerField()),
                ('estrela_2', models.PositiveSmallIntegerField()),
                ('acertos_numeros', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('acertos_estrelas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sorteio_verificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorteios.sorteio')),
            ],
            options={
                'verbose_name': 'Aposta Gerada',
                'verbose_name_plural': 'Apostas Geradas',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
