# Generated by Django 6.0.1 on 2026-01-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApostaMultipla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('estrategia', models.CharField(choices=[('frequencia', 'Baseada em Frequência'), ('equilibrada', 'Distribuição Equilibrada'), ('aleatorio', 'Aleatório Puro'), ('frios', 'Números Frios'), ('mista', 'Estratégia Mista')], max_length=20)),
                ('numeros', models.JSONField(help_text='Lista de 5 a 10 numeros')),
                ('estrelas', models.JSONField(help_text='Lista de 2 a 5 estrelas')),
                ('total_combinacoes', models.PositiveIntegerField(default=1)),
                ('custo_total', models.DecimalField(decimal_places=2, default=2.5, max_digits=10)),
            ],
            options={
                'verbose_name': 'Aposta Múltipla',
                'verbose_name_plural': 'Apostas Múltiplas',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
