# Generated by Django 6.0.1 on 2026-01-11 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteios', '0002_add_aposta_multipla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('numero_atrasado', 'Numero nao sai ha X dias'), ('jackpot_alto', 'Jackpot acima de X euros'), ('numero_saiu', 'Numero favorito saiu'), ('estrela_saiu', 'Estrela favorita saiu')], max_length=20)),
                ('parametros', models.JSONField(default=dict, help_text="Parametros do alerta (ex: {'numero': 7, 'dias': 30})")),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_disparo', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros_favoritos', models.JSONField(blank=True, default=list, help_text='Lista de numeros favoritos (1-50)')),
                ('estrelas_favoritas', models.JSONField(blank=True, default=list, help_text='Lista de estrelas favoritas (1-12)')),
                ('alertas_ativos', models.BooleanField(default=True, verbose_name='Alertas Ativos')),
                ('email_alertas', models.EmailField(blank=True, max_length=254, verbose_name='Email para Alertas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Utilizador',
                'verbose_name_plural': 'Perfis de Utilizadores',
            },
        ),
    ]
