# Generated by Django 6.0.1 on 2026-01-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApostaGeradaTotoloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros', models.JSONField()),
                ('estrategia', models.CharField(choices=[('aleatorio', 'Aleatorio'), ('frequencia', 'Numeros Frequentes'), ('equilibrada', 'Equilibrada'), ('frios', 'Numeros Frios'), ('mista', 'Mista')], max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aposta Gerada Totoloto',
                'verbose_name_plural': 'Apostas Geradas Totoloto',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticaNumeroTotoloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('frequencia', models.IntegerField(default=0)),
                ('percentagem', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ultima_aparicao', models.DateField(blank=True, null=True)),
                ('dias_sem_sair', models.IntegerField(default=0)),
                ('gap_medio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gap_maximo', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estatistica Numero Totoloto',
                'verbose_name_plural': 'Estatisticas Numeros Totoloto',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SorteioTotoloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, unique=True)),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('numero3', models.IntegerField()),
                ('numero4', models.IntegerField()),
                ('numero5', models.IntegerField()),
                ('numero_complementar', models.IntegerField(blank=True, null=True)),
                ('jackpot', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('houve_vencedor', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sorteio Totoloto',
                'verbose_name_plural': 'Sorteios Totoloto',
                'ordering': ['-data'],
            },
        ),
    ]
