# Generated by Django 6.0.1 on 2026-01-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApostaGeradaEuroDreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros', models.JSONField()),
                ('dream', models.IntegerField()),
                ('estrategia', models.CharField(choices=[('aleatorio', 'Aleatorio'), ('frequencia', 'Numeros Frequentes'), ('equilibrada', 'Equilibrada'), ('frios', 'Numeros Frios')], max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aposta Gerada EuroDreams',
                'verbose_name_plural': 'Apostas Geradas EuroDreams',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticaDreamEuroDreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream', models.IntegerField(unique=True)),
                ('frequencia', models.IntegerField(default=0)),
                ('percentagem', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ultima_aparicao', models.DateField(blank=True, null=True)),
                ('dias_sem_sair', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estatistica Dream EuroDreams',
                'verbose_name_plural': 'Estatisticas Dreams EuroDreams',
                'ordering': ['dream'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticaNumeroEuroDreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('frequencia', models.IntegerField(default=0)),
                ('percentagem', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ultima_aparicao', models.DateField(blank=True, null=True)),
                ('dias_sem_sair', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estatistica Numero EuroDreams',
                'verbose_name_plural': 'Estatisticas Numeros EuroDreams',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SorteioEuroDreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, unique=True)),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('numero3', models.IntegerField()),
                ('numero4', models.IntegerField()),
                ('numero5', models.IntegerField()),
                ('numero6', models.IntegerField()),
                ('dream', models.IntegerField()),
                ('houve_vencedor', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sorteio EuroDreams',
                'verbose_name_plural': 'Sorteios EuroDreams',
                'ordering': ['-data'],
            },
        ),
    ]
